package com.arc.model.dto.product;


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;

/*
 * 图片表
 *
 * Auto generated by mybatis-generator
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ImageDTO implements Serializable {
	private static final long serialVersionUID = 1L;

	private String ownerCode; // 当前数据拥有者的code
	private String small=""; // 小图
	private String big=""; // 大图
	private String origin=""; // 原图
	private String defaultUrl=""; // 默认图片
}
