package com.rongyi.rbac.model.vo;

import com.rongyi.rbac.model.entity.Authority;
import com.rongyi.rbac.model.entity.Role;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * Description：用户权限
 * Author:  caijie
 * History: 变更记录
 * <ModifiedBy>    <ModifiedDate>     <ModifiedVersion>
 * Administrator          2018/8/16 19:27          1.0
 * ModifiedRemark:
 * Copyright (C): 上海容易网电子商务股份有限公司
 *
 * Auto generated by fms-mybatis-generator
 */
@Data
public class RoleAuthDeatilVO implements Serializable {

        /**
         *
         */
        private static final long serialVersionUID = 4031492158951000040L;
        private Integer id;//id
        private String name;//角色名称
        private Byte status;//0启用，1停用
        private String memo;//备注
        private List<Authority> authList;//权限列表

        public RoleAuthDeatilVO(){

        }

        public RoleAuthDeatilVO(Role role){
            this.id = role.getId();//角色id
            this.name = role.getName();//角色名称
            this.status = role.getStatus();//状态 0 启用，1停用
            this.memo = role.getMemo();//备注
        }


    }
