server:
  port: 9001


spring:
  application:
    name: ms-mail
  profiles:
    #这里指定激活那个配置的空间
    active: dev

#配置日志 这里日志用xml去配置
#logback:
#  dir: /log



---
########################################################
#          不同环境         Environment for Localhost  注意：数据配置在这里
########################################################
spring:
  profiles: dev


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    #将自己的IP注册到Eureka
    prefer-ip-address: true
---

########################################################
#          不同环境         Environment for      注意：数据配置在这里
########################################################
spring:
  profiles: test
---
########################################################
#          不同环境         Environment for      注意：数据配置在这里
########################################################
spring:
  profiles: prod
