package com.rongyi.rbac.model.entity;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

/**
 * Description：系统用户表
 * Author:  caijie
 * History: 变更记录
 * <ModifiedBy>    <ModifiedDate>     <ModifiedVersion>
 * Administrator          2018/8/16 19:27          1.0
 * ModifiedRemark:
 * Copyright (C): 上海容易网电子商务股份有限公司
 *
 * Auto generated by fms-mybatis-generator
 */
@Setter
@Getter
public class User implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id; // 自增id

	private String displayName; // 账号姓名

	private String username; // 登录名

	private String password; // 密码

	private String tel; // 电话号码

	private String email; // 电子邮箱

	private boolean status=true; // 【账号状态】 (1：正常 0暂停)

	private Date createTime; // 创建时间

	private Date updateTime; // 更新时间


}
