package com.arc.model.entity.product;


import com.arc.model.entity.BaseDO;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/*
 * 图片表
 *
 * Auto generated by mybatis-generator
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Image extends BaseDO {
	private static final long serialVersionUID = 1L;

	private String ownerCode; // 当前数据拥有者的code
	private String small; // 小图
	private String big; // 大图
	private String origin; // 原图
	private String defaultUrl; // 默认图片
}
