package com.rongyi.security;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;

/**
 * 系统用户表
 *
 * Auto generated by fms-mybatis-generator
 */
@Setter
@Getter
public class User    implements Serializable {

	private static final long serialVersionUID = 1L;

	private Long id; // 自增id

	private String displayName; // 账号姓名

	private String username; // 登录名

	private String password; // 密码

	private String tel; // 电话号码

	private String email; // 电子邮箱

	private boolean status=true; // 【账号状态】 (1：正常 0暂停)

	private Date createTime; // 创建时间

	private Date updateTime; // 更新时间


}
