spring:
  application:
    name: mysql
  profiles:
    active: dev


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



########################################################
#          不同环境         Environment for Localhost  注意：数据配置在这里
########################################################
---
spring:
  profiles: dev
  servlet:
    multipart:
    max-file-size: 10200MB
    max-request-size: 102400MB

server:
  port: 80
########################################################
#          不同环境         Environment for Localhost  注意：数据配置在这里
########################################################
---
spring:
  profiles: test
