server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 3000
  port: 15033
  compression:
    enabled: true
spring:
  datasource:
    password: admin
    tomcat:
      max-idle: 10
      min-idle: 5
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      validation-query: SELECT 1
      initial-size: 5
      max-wait: 3000
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOver
    username: root
  messages:
    cache-seconds: -1
    always-use-message-format: false
    fallback-to-system-locale: true
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    show-sql: true
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      globally_quoted_identifiers: true
      use_query_cache: false
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
user:
  default:
    head: /group0/M00/00/00/wKgBq1rkIdWAOzDSAAAlObVx2-U541.png
  chaincodeUrl: github.com/hyperledger/fabric/chaincode/smartcontract
  channelName: yzhchannel
  chaincodeVersion: 1.0
  userUrl: http://192.168.1.170:8088
  chaincodeName: myfoo